In [1]:
#Numpy 패키지 import

import numpy as np

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

In [4]:
#벡터화연산

data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
x = np.array(data)
x

#배열 type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

#list type

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [9]:
2 * a + b

array([12, 24, 36])

In [10]:
a == 2 

array([False,  True, False])

In [11]:
b > 10

array([False,  True,  True])

In [12]:
(a == 2) & (b > 10)

array([False,  True, False])

In [13]:
c = np.array([[0, 1, 2], [3, 4, 5]]) 
c

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
#행의 갯수

len(c)

2

In [15]:
#열의 갯수 

len(c[0])

3

In [16]:
#배열의 차원과 크기 알아내기 

print(c.ndim)
print(c.shape)

2
(2, 3)


In [17]:
#배열 슬라이싱

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
a[:, 1]    # 두번째 열 전체 

array([1, 5])

In [19]:
a[:2, :2]  #두번째 행, 열 까지 

array([[0, 1],
       [4, 5]])

In [20]:
#배열 인덱싱

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
#사용하는 원소의 갯수가 정해저 있기 때문에 
#reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다. 
#-1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용된다.

a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [30]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [31]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [32]:
x[:, np.newaxis]

# 같은 배열에 대해 차원만 1차원 증가시키는 경우에 적용.

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [35]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.dstack([c1, c2])

#(3,4,2) 형태가 됨

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [38]:
c = np.stack([c1, c2])
c

#(2,3,4) 형태가 됨

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
c = np.stack([c1, c2], axis=1)
c

#(3x4)  형태에서 (3x2x4) 형태로 바뀜 

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [40]:
# r_ method (좌우 연결)

np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

#method 이지만 대괄호를 사용 <- 인덱서 라고 일컬음 

array([1, 2, 3, 4, 5, 6])

In [41]:
# c_ method (차원을 증가시킨 후 좌우로 연결)

np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

#method 이지만 대괄호를 사용 <- 인덱서 라고 일컬음 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
# title method (동일한 배열을 반복하여 연결)

a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

#method 이지만 대괄호를 사용 <- 인덱서 라고 일컬음 

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [43]:
#2차원 그리드 포인트 생성 

x = np.arange(3)
x

array([0, 1, 2])

In [44]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [47]:
X, Y = np.meshgrid(x, y)

In [48]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [49]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [50]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]