In [1]:
np.random.seed(0)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [5]:
np.random.seed(100)

In [6]:
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [7]:
np.random.seed(0)

In [8]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [9]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [10]:
np.random.choice(5, 5, replace=False)   #shuffle 명령과 같다. 

array([2, 4, 3, 0, 1])

In [11]:
np.random.choice(5, 3, replace=False) #3개선택

array([3, 1, 4])

In [12]:
np.random.choice(5, 3, replace=False) #3개선택

array([0, 4, 2])

In [13]:
np.random.choice(5, 3, replace=True) #3개선택, True는 선택 데이터 다시 선택 가능

array([0, 1, 1])

In [14]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  #선택확률을 다르게해서 10개 선택 

array([3, 3, 2, 3, 2, 3, 2, 2, 2, 2], dtype=int64)

In [15]:
np.random.rand(10)

array([0.22232139, 0.38648898, 0.90259848, 0.44994999, 0.61306346,
       0.90234858, 0.09928035, 0.96980907, 0.65314004, 0.17090959])

In [16]:
np.random.randn(10)

array([ 1.29269823, -0.73145824, -1.60540226,  0.98947618,  0.11081461,
       -0.38093141,  0.11495917,  0.34531264, -1.73495876,  1.65835111])

In [17]:
np.random.randn(3, 5)

array([[ 2.29977152, -0.47113526,  1.26271548, -1.17051545,  1.0657892 ],
       [-0.69993739,  0.14407911,  0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241, -0.36326702, -0.01234481]])

In [3]:
np.random.randint(10, size = 10)

array([2, 2, 4, 2, 5, 8, 1, 6, 2, 8])

In [4]:
np.random.randint(10, 20, size = 10)

array([12, 12, 17, 16, 16, 16, 13, 16, 15, 10])

In [6]:
np.random.randint(10, 20, size=(3, 5))

array([[16, 13, 13, 18, 16],
       [16, 16, 16, 15, 11],
       [19, 12, 14, 18, 12]])

In [7]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [8]:
a  = np. array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [10]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [11]:
count

array([2, 2, 1], dtype=int64)

In [12]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)